name: Deploy to Vultr Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        script: |
          # --- Frontend Deployment ---
          echo ">>> Deploying Frontend..."
          cd ~/k-news-frontend
          git pull
          npm install
          npm run build
          pm2 restart k-news-frontend

          # --- Backend Deployment ---
          echo ">>> Deploying Backend..."
          cd ~/seoulsync/backend
          git pull  # ecosystem.config.js 파일을 포함한 최신 코드를 받음
          pm2 startOrRestart ecosystem.config.js # 설정 파일로 재시작

          # pm2 설정 저장
          pm2 save
          
          # pm2 설정 저장
          pm2 save
          
          echo ">>> Deployment Finished!"